#!/bin/python3

import os
import sys

def acmTeam(topic):
    n = len(topic)
    max_topics = 0
    team_count = 0

    for i in range(n):
        for j in range(i+1, n):
            known = bin(int(topic[i], 2) | int(topic[j], 2)).count("1")
            
            if known > max_topics:
                max_topics = known
                team_count = 1
            elif known == max_topics:
                team_count += 1
    
    return [max_topics, team_count]


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n, m = map(int, input().split())

    topic = []
    for _ in range(n):
        topic.append(input().strip())

    result = acmTeam(topic)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
