#!/bin/python3

import os
import sys

#
# Complete the 'climbingLeaderboard' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER_ARRAY ranked
#  2. INTEGER_ARRAY player
#

def climbingLeaderboard(ranked, player):
    # Remove duplicates and sort descending
    scores = sorted(list(set(ranked)), reverse=True)
    n = len(scores)
    results = []
    index = n - 1  # Start from the lowest score in ranked
    
    for p in player:
        # Move up the leaderboard while player score is >= ranked score
        while index >= 0 and p >= scores[index]:
            index -= 1
        # If index == -1, player is at the top
        results.append(index + 2)
    
    return results


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ranked_count = int(input().strip())
    ranked = list(map(int, input().rstrip().split()))

    player_count = int(input().strip())
    player = list(map(int, input().rstrip().split()))

    result = climbingLeaderboard(ranked, player)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
