#!/bin/python3

import os
import sys

#
# Complete the 'designerPdfViewer' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY h
#  2. STRING word
#

def designerPdfViewer(h, word):
    # Each letter corresponds to an index: 'a' -> 0, 'b' -> 1, ..., 'z' -> 25
    # Find the tallest letter height in the word
    max_height = max(h[ord(c) - ord('a')] for c in word)
    # The area is tallest height * length of the word
    return max_height * len(word)


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    h = list(map(int, input().rstrip().split()))  # heights of all 26 letters

    word = input().strip()  # the given word

    result = designerPdfViewer(h, word)

    fptr.write(str(result) + '\n')

    fptr.close()
