#!/bin/python3

import os
import sys

# Complete the jumpingOnClouds function below.
def jumpingOnClouds(c, k):
    n = len(c)
    energy = 100
    pos = 0
    
    while True:
        pos = (pos + k) % n   # jump to next cloud
        energy -= 1 + 2 * c[pos]   # decrease energy
        if pos == 0:   # back to start
            break
    return energy


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()
    n = int(nk[0])
    k = int(nk[1])

    c = list(map(int, input().rstrip().split()))

    result = jumpingOnClouds(c, k)

    fptr.write(str(result) + '\n')
    fptr.close()
