#!/bin/python3

import math
import os
import random
import re
import sys

def nonDivisibleSubset(k, s):
    remainder_count = [0] * k
    for num in s:
        remainder_count[num % k] += 1

    result = min(remainder_count[0], 1)

    for r in range(1, (k // 2) + 1):
        if r != k - r:
            result += max(remainder_count[r], remainder_count[k - r])
        else:
            result += 1

    return result

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])
    k = int(first_multiple_input[1])

    s = list(map(int, input().rstrip().split()))

    result = nonDivisibleSubset(k, s)

    fptr.write(str(result) + '\n')
    fptr.close()
