#!/bin/python3

import os
import sys

def organizingContainers(container):
    n = len(container)
    container_capacity = [sum(row) for row in container]
    type_count = [sum(container[i][j] for i in range(n)) for j in range(n)]
    return "Possible" if sorted(container_capacity) == sorted(type_count) else "Impossible"

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        n = int(input().strip())
        container = []
        for _ in range(n):
            container.append(list(map(int, input().rstrip().split())))

        result = organizingContainers(container)

        fptr.write(result + '\n')

    fptr.close()
