#!/bin/python3

import os
import sys

#
# Complete the 'pickingNumbers' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def pickingNumbers(a):
    # Sort the array
    a.sort()
    max_length = 0
    
    # For each number, count how many numbers are within difference <= 1
    for i in range(len(a)):
        count = 0
        for j in range(i, len(a)):
            if abs(a[j] - a[i]) <= 1:
                count += 1
        max_length = max(max_length, count)
    
    return max_length


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())
    a = list(map(int, input().rstrip().split()))

    result = pickingNumbers(a)

    fptr.write(str(result) + '\n')

    fptr.close()
