#!/bin/python3

import math
import os
import random
import re
import sys

def repeatedString(s, n):
    count_in_s = s.count('a')
    full_repeats = n // len(s)
    remainder = n % len(s)
    count_in_remainder = s[:remainder].count('a')
    return count_in_s * full_repeats + count_in_remainder

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()
    n = int(input().strip())

    result = repeatedString(s, n)

    fptr.write(str(result) + '\n')
    fptr.close()
