#!/bin/python3

import os
import sys

#
# Complete the 'saveThePrisoner' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n (number of prisoners)
#  2. INTEGER m (number of sweets)
#  3. INTEGER s (starting chair)
#

def saveThePrisoner(n, m, s):
    # Calculate the prisoner to warn
    result = (s + m - 1) % n
    if result == 0:
        return n
    else:
        return result


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        first_multiple_input = input().rstrip().split()

        n = int(first_multiple_input[0])
        m = int(first_multiple_input[1])
        s = int(first_multiple_input[2])

        result = saveThePrisoner(n, m, s)

        fptr.write(str(result) + '\n')

    fptr.close()
