#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'simpleArraySum' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY ar as parameter.
#

def simpleArraySum(ar):
    # Return the sum of all elements in the array
    return sum(ar)

if __name__ == '__main__':
    # If you're testing locally and not in a HackerRank environment, you can use this:
    # OUTPUT_PATH = 'output.txt'
    # os.environ['OUTPUT_PATH'] = OUTPUT_PATH

    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ar_count = int(input().strip())

    ar = list(map(int, input().rstrip().split()))

    result = simpleArraySum(ar)

    fptr.write(str(result) + '\n')

    fptr.close()
