#!/bin/python3

import os
import sys

#
# Complete the 'utopianTree' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER n as parameter.
#

def utopianTree(n):
    height = 1  # Initial height of the tree
    for cycle in range(1, n + 1):
        if cycle % 2 == 1:  # Odd cycle -> Spring (double height)
            height *= 2
        else:               # Even cycle -> Summer (increase by 1)
            height += 1
    return height


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())  # Number of test cases

    for t_itr in range(t):
        n = int(input().strip())  # Number of growth cycles

        result = utopianTree(n)

        fptr.write(str(result) + '\n')

    fptr.close()
