#!/bin/python3

import os
import sys

#
# Complete the 'viralAdvertising' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER n as parameter.
#

def viralAdvertising(n):
    shared = 5       # Day 1 starts with 5 people
    cumulative = 0   # Total likes
    
    for _ in range(n):
        liked = shared // 2      # Half of the shared people like the ad
        cumulative += liked      # Add to total likes
        shared = liked * 3       # Each liked person shares with 3 friends
    return cumulative


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    result = viralAdvertising(n)

    fptr.write(str(result) + '\n')

    fptr.close()
